apiVersion: v1
kind: Service
metadata:
  name: pingg-node-graph-service
spec:
  ports:
    - protocol: TCP
      targetPort: 9000
      port: 9000
  selector:
    app: pingg-node-graph
  type: LoadBalancer