apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    masterauth 2817bx33819nzxshqbj2098uwqjldwp928e38y4621
    requirepass 2817bx33819nzxshqbj2098uwqjldwp928e38y4621
    bind 0.0.0.0
    port 6379
    daemonize yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename "dump.rdb"
    dir "/data"
    appendonly yes
    appendfilename "appendonly.aof"
    loadmodule /etc/redis/redisgraph.so