apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: module-maker-cluster
spec:
  serviceName: module-maker-cluster
  replicas: 1
  selector:
    matchLabels:
      app: module-maker-cluster
  template:
    metadata:
      labels:
        app: module-maker-cluster
    spec:
      containers:
      - name: module-maker
        image: us.gcr.io/cs1530group11/redis-module-maker-03
        env:
          - name: REDIS_PASSWORD
            value: x95b1x91zbJu9ws217eyu299y2047hd21io1nsq
        volumeMounts:
        - name: data
          mountPath: /data
          readOnly: false
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
